# version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: resource_estimator
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U 'enter username' -d resource_estimator"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build: ./cc-backend
    # container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/resource_estimator
      SPRING_DATASOURCE_USERNAME: 
      SPRING_DATASOURCE_PASSWORD: 
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    restart: always
    networks:
      - appnet
  
  frontend:
    build: ./ccfrontend
    # container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet: 
    driver: bridge

volumes:
  postgres_data:
